mattermost/mattermost-mattermod

config/instance-setup.sh

As Corey suggested, this change the config to use sampledata generation to pre-populate spinmint servers.

Use sampledata generation on spinmint instances start

---

config/config-mattermod.json
server/config.go
server/github.go
server/issue.go
server/log.go
server/pull_request.go
server/server.go
server/spinmint.go
store/sql_store.go
store/store.go

This PR drops the use of l4g (unmaintained) and replace it by mlog, which is Mattermost wrapper around Uber's zap logging lib.
The original ticket suggested to include a CLI to pull or monitor logs or factor out mlog out of Mattermost code base.
I'm more inclined for factoring out mlog and could even lead the effort if necessary. IMO having a few CLI for mlog would be best.
[MM-11148](https://mattermost.atlassian.net/browse/MM-11148)

[MM-11148] Convert mattermod to use structured logging #10315

---

server/test_servers_experimental.go

This prevents conflicts with multiple repos creating the same dns entry.

Tag the dns with repo name

---

server/pull_request.go
server/test_servers_experimental.go

This change moves mattermod over to using copies of the structs
that are used by the provisioning server in the mattermost-cloud
repo. This helps make mattermod less brittle when interacting with
provisioning servers.
This change also cleans up some logging and messages sent to PRs.

Use mattermost-cloud request objects

---

server/cherry_pick.go

when cherry pick fail dont post to mattermost channel the error message is posted to the github pr and that is enough

remove post to mattermost when cherry pick fail

---

cloud/installation.go
cloud/models.go
mattermod.go
model/pull_request.go
server/cherry_pick.go
server/cla.go
server/config.go
server/github.go
server/github_pr.go
server/issue.go
server/limit_rate_gh.go
server/pull_request.go
server/server.go
server/spinmint.go
server/spinwick.go
server/spinwick_test.go
server/utils.go
server/webhook.go

The intention of this PR is to remove mattermod tech debt in order to 
provide a foundation for a better SpinWick experience. The primary
goal of this work was to begin addressing some of the race conditions
that exist when working with SpinWicks.
The following was included in these commits: 
- Enhanced Server struct and changed all related functions to
methods of Server. The Server object is no longer a shared
variable.
- Moved the server config to belong to the server struct and not
be a shared variable.
- Provided a way to cleanly create, start, and stop a server.
- Resolved issues with not returning errors when we should be.
- Refactors the spinwick code to no longer require the mattermod
database.
- Cleans up logic for creating, updating, and deleting SpinWicks
to primarily occur as …

[MM-17073] Mattermod Refactor #2

---

server/github.go
server/pull_request.go
server/spinwick.go

- when a spinwick fail remove the label and the comments when requesting for the first time

remove label when test server fail and do some comments cleanup

---

server/spinwick.go

- add a sha in the comment when we update the test server
- remove old update test server messages to avoid confusion and make the PR a bit cleaner.

add sha in the update server message and remove old comments

---

server/spinwick.go

the wait for image was just applied for the create spinwick and not in the upgrade process

fix upgrade to wait for an image

---

config/config-mattermod.json
go.mod
go.sum
model/pull_request.go
server/circleci.go
server/config.go
server/github.go
server/pull_request.go
server/spinmint.go
store/sql_pull_request_store.go
vendor/github.com/cpanato/go-circleci/CHANGELOG.md
vendor/github.com/cpanato/go-circleci/LICENSE
vendor/github.com/cpanato/go-circleci/README.md
vendor/github.com/cpanato/go-circleci/circleci.go
vendor/modules.txt

Context:
we have circleci for our CI pipelines for almost all public repos we have.
In circleci we use the feature called `context` which inject environment variables in the build, this env var contains some secrets to upload data to s3 or push docker images. This does not work when the build is running from a Fork/PR.
This PR fixes this issue we have that every time someone from the org needs to retrigger the job if that comes from a PR/Fork
this retriggers the job and the previous one will be canceled.
next: add a slash command to retrigger the build if that fail

Fix permission issues from PR/Forks triggering the circleci job with a org member

---

model/pull_request.go
server/community.go
server/github.go
server/pull_request.go

When a new PR in October is created and the contributor is not a GitHub org member, Mattermod now adds the `Hacktoberfest` label. This should make sure, we don't forget it.
cc @amyblais @jasonblais

Automatically add Hacktoberfest label to new community PRs

---

server/server.go
server/update_branch.go

This adds the ability to update the PR with the latest upstream.
this is handy when the Core Members need to merge a PR and that needs an update.
the command is `/update-branch` and will try to update the branch if it fails will post a message and you will need to do manually

add update branch command

---

server/circleci.go

The issue we have is that we were checking the commits for a PR and when doing that it will check the commits that came from a merge (to update the PR with the lastest master or another branch) and in those commits, it might contain the blacklisted file.
So now we are getting the files modified or added for that PR, it will return only the files in the PR and not the merge commits.

fix the file check, getting the list of files for a PR

---

server/spinwick.go

On heavily-loaded clusters, this may not be quite enough time for
an installation to reconcile. This change increases the timeout
to address that possibility.

Increase installation reconciliation timeout

---

go.mod
go.sum
server/builds.go
vendor/github.com/mattermost/mattermost-server/LICENSE.txt
vendor/github.com/mattermost/mattermost-server/NOTICE.txt
vendor/github.com/mattermost/mattermost-server/mlog/default.go
vendor/github.com/mattermost/mattermost-server/mlog/global.go
vendor/github.com/mattermost/mattermost-server/mlog/log.go
vendor/github.com/mattermost/mattermost-server/mlog/stdlog.go
vendor/github.com/mattermost/mattermost-server/mlog/sugar.go
vendor/github.com/mattermost/mattermost-server/mlog/testing.go
vendor/modules.txt

Not sure why the tags request was failing (happened locally for me too) but this is a better way to do it anyways. Tested locally.

Instead of listing all docker tags for a repo, check if the manifest is available for that tag

---

server/build_mobile_apps.go
server/github.go

Using the wrong username for the api call. 
works:
https://api.github.com/repos/mattermost/mattermost-mobile/commits/2d8d8053f13df14b2defa56d0bb89895131deb1f/status
not working: 
https://api.github.com/repos/enahum/mattermost-mobile/commits/2d8d8053f13df14b2defa56d0bb89895131deb1f/status

Fixing wrong username for api call.

---

server/integrations.go

There is too much unnecessary output in the logs, they were good for debugging. 
Remove some of them.

Remove too much debugging information

---

server/build_mobile_apps.go

Context with timeout for building the IOS app is too low. Increased now to 2 hours.  
https://github.com/mattermost/mattermost-mobile/pull/4047

Increase the context timeout for the ios building. #4047

---

server/circleci.go
server/enterprise.go
server/pull_request.go
server/server.go

Triggering the ee tests from a server PR will look for the same named enterprise branch, if this branch exists in the upstream. 
Refactors the the branching logic. 
Removes the jenkins github status auto succeed.

Trigger ee tests with appropriate ee branch or fallback to base branch. 

---

.gitignore
mattermod.go

We were listening to the same signal. This PR fixes that
to listen for other appropriate signals.
We make one more small, unrelated change to add the config file
to .gitignore.
https://mattermost.atlassian.net/browse/MM-26379

MM-26379: remove duplicate os.Interrupt signals

---

server/cla.go
server/webhook.go

Improves the way we close some connections:
- Draining the body before closing the connection
- Using defer to close the connection
https://mattermost.atlassian.net/browse/MM-26384

[MM-26384] Improve close http connections

---

server/auto_merge.go
server/builds.go
server/github.go
server/issue.go
server/pull_request.go
server/spinmint.go
store/sql_issue_store.go
store/sql_pull_request_store.go
store/sql_spinmint.store.go
store/store.go

Mattermod still uses the old architecture of spawning a goroutine
for each store method and waiting for it. The server codebase has migrated from it,
but this is still lagging behind.
This PR makes the change to convert all store methods to be synchronous.
https://mattermost.atlassian.net/browse/MM-26419

MM-26419: make store methods synchronous

---

Makefile
server/server.go
server/server_test.go

This PR removes global state form `server_test` and also slims down the test to actually test the `ping()` endpoint. There were too much initialization and complexity for only testing a single endpoint. If server is need to be tested, it should be handled in a different test.
https://mattermost.atlassian.net/browse/MM-26383

[MM26383] server/server_test: remove globals and slim down tests

---

server/builds.go
server/builds_mocked.go

This PR removes `dockerRegistryClient` code from `server/builds.go` which is not used anywhere.
<!--
https://mattermost.atlassian.net/browse/MM-26382

[MM-26377] server/builds: remove unnecessary code

---

mattermod.go
server/cherry_pick.go
server/server.go

This PR remove `manners` for `http.Server` shutdown. Also moved `rand.Seed()` into more convenient place. Did some cleanup in the server struct.
https://mattermost.atlassian.net/browse/MM-26380

[MM-26380] Replace manners with standard library shutdown

---

store/sql_store_test.go

This PR lets define another root user that is different than root to execute the tests.
The motivation behind this PR is that I'm using a docker image for mysql that has the root user in localhost and I've created a mattermod user with admin permissions and I need this changes to make it work:
```
$ MYSQL_ROOT_USER=mattermod MYSQL_ROOT_PASSWORD=mattermod make test
Running Go tests
/usr/local/go/bin/go test github.com/mattermost/mattermost-mattermod/cmd/mattermost-mattermod github.com/mattermost/mattermost-mattermod/model github.com/mattermost/mattermost-mattermod/server github.com/mattermost/mattermost-mattermod/server/mocks github.com/mattermost/mattermost-mattermod/store github.com/mattermost/mattermost-mattermod/store/mocks
? …
```

Allow other user to be the root

---

server/cherry_pick.go
server/cla.go
server/pull_request.go

We passed several contexts to goroutines. Therefore when the parent
function returned, the context got cancelled and therefore the running
goroutines would throw an error. To fix this:
- We remove passing the context in checkIfNeedCherryPick. This is not
ideal and every call should take the parent context. The problem is that
a request handler is semi-synchronous. It does some jobs synchronously and
spins of time taking jobs in goroutines without any control of how to shut
them down.
What we need is to make the entire event handler async, and create a context
inside that and run everything synchronously inside that. Until we have that,
we need to make do with this.
- We make createCLAPendingStatus synchronous. This also fixes a long-standing
bug where the CLA check would randomly go to a …

MM-26797: Fix context cancellation on goroutines

---

server/auto_merge.go
server/pull_request.go

There's no need to remove a label after doing auto-merge, because
it already gets removed as part of a cleanup label process when a PR
is closed.
This fixes a race condition where we were trying to remove the same label twice,
generating logs like this:
```
ERRO[2020-07-09T18:54:14.659247+05:30] Error removing the label                      caller="server/github.go:129" error="DELETE https://api.github.com/repos/mattermost/mattermost-server/issues/14970/labels/AutoMerge: 404 Label does not exist []
```
While here, we add a continue statement to quickly move forward.
https://mattermost.atlassian.net/browse/MM-26820

MM-26829: Fix duplicate label removal

---

.circleci/config.yml
Dockerfile
Makefile

Containerizing `mattermod`. As a result two extra Makefile targets adde:
- `make docker`: to build the docker image
- `make push`: to push docker image to DockerHub
Example usage:
```bash
DOCKER_TAG=latest make docker push
```

Containerize mattermod

---

server/issue.go
server/pull_request.go
server/server.go

Added error propagation to the issue event handler. The ticket was originally for a logical error in the `server.githubEvent`, but it is taken care in #168 so I added a small refactor around error handling instead.
https://mattermost.atlassian.net/browse/MM-26819

[MM-26819] server: add some error propogation to handleIssueEvent

---

server/pull_request.go

This PR changes the way we check if the event has Auto Merge label. Currently we are checking every label for any `labeled` action. And it seems like we are receiving this event multiple times (actually, number of labels times). Thus, we send "Will try to auto merge..." message several times. This change will focus on the specific event for the actual Auto Merge label.
https://mattermost.atlassian.net/browse/MM-26815

[MM-26815] server/pull_request: tweak auto merge label handling

---

server/circleci.go

There is still a config setting for mattermod called "Blacklist" but I haven't changed it because that would break the API.

Replacing blacklist with blocklist where is possible without braking the API

---

.gitignore
deploy/overlays/prod/kustomization.yaml

For security reason we can only place config files in or under current kustomization folder, as such `deploy/overlays/prod/` cannot access gitignored config files under `deploy/config/`

Fix placement of production config files

---

server/validate_signature.go
server/validate_signature_test.go

#184 added middleware validation which this PR skips that only for `/healthz` endpoint.

Skip webhook SHA validation for /healthz

---

server/server.go

Just the error only contains the title "Nil pointer dereference".
We log the full stack trace for full visibility.

Properly log the full panic trace

---

server/update_branch.go
server/update_branch_test.go

The original code didn't comment when the error contained
"job scheduled on GitHub side; try again later"
```
if !strings.Contains("job scheduled on GitHub side; try again later", err.Error()) {
msg := fmt.Sprintf("Error trying to update the PR.\nPlease do it manually.\nError: %s", err.Error())
s.sendGitHubComment(ctx, pr.RepoOwner, pr.RepoName, pr.Number, msg)
}
```
But we did not reset the err variable, which attempted to comment with an empty message.
We fix this by setting err to nil.

MM-27189: Fix comment with empty body

---

server/server.go

When parsing slash commands, all of them are from pull requests.
Therefore, we just ignore everything if it's not a pull request.
https://mattermost.atlassian.net/browse/MM-27373

MM-27373: Ignore comments coming from issues

---

server/github.go
server/issue_handler_test.go

Yet another regression found during local testing for #186. In some cases GitHub does not adding Repository field for issues in webhook requests. In those cases, we try to parse the `htmlURL` to get repo name and repo owner.

server: fix gh issue service error if there isnt repo field in issue

---

Dockerfile
Tiltfile
config/config-mattermod.default.json
deploy/base/app/deployment.yaml
deploy/base/app/service.yaml

Exposing `/metrics` endpoint internally for Promethues to scrape them later on.

Expose /metrics endpoint to be scraped later on

---

metrics/provider.go
server/metrics.go

This PR includes some fixes to the metrics:
- Fixed the missing registration of the githubCache metrics
- Fixed the order of parameters in github metrics that was wrong and was sending the method to the handler and other way around
- Reduce the path string to avoid too much unnecessary information as you can see in the next screenshot:
now we plan to store "/repo/{user|org}/{repository}/{api_endpoint}" where api_endpoint could be something like: issues, branches, etc
https://mattermost.atlassian.net/browse/MM-27431

[MM-27431] Multiple metrics fixes

---

server/cherry_pick.go

The production instance of mattermod seems to think that some merged and closed PRs have been closed but not merged. The closing of the PR triggers the event in mattermod, which then queries Github to check if the PR has been merged. The response from Github appears to be that the PR was not merged, although manually checking the API response from Github a little while later shows that the event has been merged. 
This leads me to suspect a caching issue. In this PR mattermod uses the merge state information from the event itself instead of querying Github again. According to the Github docs [1][2], the event contains all the information we need so we should not need to query Github again. 
[1] https://developer.github.com/webhooks/event-payloads/#pull_request 
[2] …

use PR from event when checking if PR is mergeable

---

server/cherry_pick.go

This check just blindly looks for `math/rand` usage. At this point we don't need to check this.

server/cherrypick: suppress linter error

---

server/issue_comment_handler.go
server/issue_comment_handler_test.go

This PR adds prevention of triggering commands again when they are deleted.
https://mattermost.atlassian.net/browse/MM-27706

[MM-27706] server/issue_comments: ignore deleted comments

---

server/circleci.go
server/cla.go
server/github.go
server/issue_handler.go
server/issue_handler_test.go
server/pagination_test.go
server/pull_request.go
server/server.go

We use pagination for all API calls which are liable to return
more than 30 items.
https://mattermost.atlassian.net/browse/MM-26455

MM-26455: Use pagination for long API calls

---

server/config.go
server/enterprise.go

This PR adds two things:
- Debug logs for GH requests
- Increase the default timeout for cron tasks. Looks like we're getting timeouts since we added the pagination to get all the results

Add logs and increase default cron task timeouts

---

.golangci.yml
config/config-mattermod.default.json
server/cherry_pick.go
server/config.go

- If the repo folder is not present locally, we clone it
and then set the upstream remote.
- While here, we also return error from returnToMaster function.
- And also, use CombinedOutput instead of Output which contains
output from standard error also. This can be helpful to debug errors.
https://mattermost.atlassian.net/browse/MM-27264

Clone git repos if they are not present locally

---

server/server.go

If a rate limit error occurs, we would just blindly retry that request
without incrementing the page number. This would keep retrying the same page
until GH would eventually return a proper response or return NextPage = 0.
A better way is to move on to the next page so that even if an error occurs,
we eventually converge to getting out of the loop.
While here, we also add some sleeps to better manage rate limit errors.
Ideally, we would just tune the burst rate, but for now we are sharing the same config
for both Job server and API server. To keep things simple, we change the code.

Bump page number while continuing in case of error

---

server/circleci.go
server/circleci_test.go

Look for the page token and go through all the pages
until we get the workflow id.
We also bring back the API retry logic which got removed
when we moved to use the circleCI API.
https://mattermost.atlassian.net/browse/MM-27539

MM-27539: Use pagination for s.waitForWorkflowID

---

server/cherry_pick.go
server/cherry_pick_test.go

We check if a release string is present or not before continuing
with the cherry pick request.
https://mattermost.atlassian.net/browse/MM-28886

MM-28886: Fix panic on out-of-bounds error

---

.goreleaser.yml
Makefile

PR adds a `publish-release` target to the `Makefile` that uses [Goreleaser](https://goreleaser.com/) to simplify the publishing of new releases.
This was used to generate [v0.5.0](https://github.com/mattermost/mattermost-mattermod/releases/tag/v0.5.0).

Simplify release publishing

---

server/community.go

See https://hacktoberfest.digitalocean.com/hacktoberfest-update
If a PR is deemed invalid, we can simply remove this label and add the 'invalid' label instead.

Add 'hacktoberfest-accepted' label instead of 'hacktoberfest' label in PRs

---

deploy/overlays/prod/kustomization.yaml

Currently, there are 3 replicas in production with one PVC shared with all of them. This PVC has to be of type `ReadWriteOnce` because all of the pods need to be able to write to it and as such, the volume is _bound_ to one specific node and there have been multiple `FailedScheduling` issues in the past couple of deployments. This is to reduce the replicas to 1 (for now) to make the pod _moveable_ between nodes.

Temporary reduce prod replicas to 1 due to pvc issue

---

.gitignore
server/pull_request_handler.go
server/pull_request_handler_test.go

Right now we're comparing pointers which is probably not the behavior we want
```go
// server/pull_request_handler.go
//...
if oldPr.MaintainerCanModify == nil || (oldPr.MaintainerCanModify != pr.MaintainerCanModify) {
prHasChanges = true
}
//...
```
I was gonna commit the change in #257 but I wasn't quick enough :)
JIRA: https://mattermost.atlassian.net/browse/MM-26814

Dereference pointers when comparing MaintainerCanModify

---

hack/release.sh

when I was running the release notice the goreleaser part failed because the repository was dirty,
on macOS looks like when doing the sed part it generates a temporary file.
This PR removes that file to not fail the release process
The error log below
```
$ make minor
==> Commit changes for release version v0.7.0
[master e195ade] Release version v0.7.0
1 file changed, 2 insertions(+), 2 deletions(-)
==> Push commits for v0.7.0
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 16 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 1.14 KiB | 1.14 MiB/s, done.
Total 6 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To …
```

remove temporary file when running on macos

---

hack/cherry-pick.sh

This commit modifies the cherry-pick script to add the `release-note` block
with `NONE` to the PR body.
Fixes https://mattermost.atlassian.net/browse/DOPS-502

DOPS-502 Add release-note block to cherry-pick script

---

server/circleci.go
server/circleci_test.go

Previously we were returning the Id of the job that we triggered and not the workflow ID, this PR fix that
I test spinning a local bot and triggered and I got the correct URL to open in circleci
n/a

return the correct workflow ID

---

server/review.go
server/review_test.go

I think everyone should be aware of the logging guidelines so far. Let's review this for non-org members.

Do not review mlog changes for organization members

---

server/circleci.go
server/e2e_test_command.go
server/github.go

The waiting for a GitHub status polling stresses the secondary rate limit https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits.
Until we implement the `Retry-After` into the GitHubClientWithLimiter, let's decrease the stress.

Extend polling interval to 30 secs instead of 5 secs

---

server/gitlab.go

Fixes
```
ERROR:  null value in column \\\"variable_type\\\" violates not-null constraint\\n
```
when triggering GitLab side. It seems to not be optional anymore compared to https://docs.gitlab.com/ee/api/pipelines.html#create-a-new-pipeline
Fixes https://github.com/mattermost/mattermost-server/issues/XXXXX
Otherwise, link the JIRA ticket.
-->

Fix not-null constraint violation

---

server/e2e_cancel.go
server/gitlab.go
server/issue_comment_handler.go

- Fix when bot comments, /e2e-cancel command gets run :grimacing:  
- Fix listing pipelines for wrong ref, so no pipelines were found (pr ref instead of e2e-webapp-pr ref in the cypress project)

Fixes for /e2e-cancel command

---

server/e2e_test_command.go
server/e2e_test_command_test.go
server/github.go

I merged this PR (https://github.com/mattermost/mattermost-mattermod/pull/299/files) recently to fix the e2e-test spam messages, when a PR is not in a ready state. 
Turns out that polling now for the CI status is completely broken. 
Honestly, I am guessing on what the fix is. The answer is immediate, there is no attempt or log message to even try to poll. It might be that I tried to use the `context.WithDeadline` compared to what we usually use is `context.WithTimeout`. I also unnecessarily changed getting instead of the list of statuses for the sha to ref, which I also revert with this PR.

Fix polling for github status for e2e testing.

---

server/config.go
server/e2e_test_command.go
server/e2e_test_command_test.go
server/github.go

This is a partial revert, fixing the e2e-spam, but not using the specific GitHub status context to only require docker build steps to pass. The whole CI pipeline still needs to pass.

Revert using combined status instead of specific github status context.

---

server/fast_forward.go
server/fast_forward_test.go

Adds a `--dry-run` flag to the /cloud-ff command.
https://mattermost.atlassian.net/browse/MM-43738

server/fast_forward: add --dry-run flag to fast-forward process

---

cmd/mattermost-mattermod/main.go

Mattermod only fetchs GitHub Organisational Members at startup and there is no refresh mechanism inside. However Mattermod-jobserver fetches members everyday. This causes redeployment of mattermod for new Github members.  
This PR contains cron job to refresh members everyday for mattermod.
Jira: https://mattermost.atlassian.net/browse/DOPS-971

Add Github Organisation Member Refresh for new Members

---

server/translations.go

This PR fixes automatic label assignment for non-translation-PRs.
We added mattermod to add a label `Do Not Merge/Mattermod` for translation prs. Cause of negative check it assings that label to every other PR.
Issue can be seen at this PR label history.

Fix automatic translation PR assignment

---

cmd/jobserver/main.go
metrics/server.go
server/fast_forward.go
server/fast_forward_test.go
server/github_client.go
server/mocks/github_client.go
server/server.go

We create a cron job that will once a month
and clean up old branches.
Also fix an unrelated bug with resp.NextPage.
We need to check for NextPage == 0, _after_
processing the current batch, not before. This
skips the last batch of items.
https://mattermost.atlassian.net/browse/MM-43288

MM-43288: Cleanup old cloud branches

---

server/cherry_pick.go

The `getMilestone` function adds a prefix to every mileston and generates the target
branch with `release-*`. The `cloud` branch hasn't any prefix so that's why it fails
when we try to use the label cherry pick functionality.
Ticket: https://mattermost.atlassian.net/browse/CLD-4001

Fix broken cherry-pick functionaliy for label `CherryPick/Approved`

---

.golangci.yml
server/cla.go
server/metrics.go
server/review.go
server/server.go
server/server_test.go
server/validate_signature.go

After Go 1.16 the `io/ioutil` has been deprecated and the Golang CI lint is failing.
Replaced all the references to make CI back to green.
Ticket: https://mattermost.atlassian.net/browse/CLD-4064

Migrate from deprecated `io/ioutil` to `io`

---

config/config-mattermod.default.json
server/config.go
server/e2e_test_command.go
server/e2e_test_command_test.go
server/gitlab.go

Added link to Test Dashboard which now supports `https://automation-dashboard.vercel.app/cycle/<pipeline_id>`, ex. `https://automation-dashboard.vercel.app/cycle/266131`. See related changes in the dashboard [here](https://github.com/saturninoabril/automation-dashboard/commit/249f0b58db98a33d59593bb43f9f92c74bc83b1a#diff-6aad13058d521d590690e9502805c3238ad0c08a06d9cd08e66dd2298828f101R1-R15).
Once triggered, it will post a comment like the following:
```markdown
Successfully triggered E2E testing!
[GitLab pipeline](https://git.internal.mattermost.com/qa/cypress-ui-automation/-/pipelines/266131) | [Test dashboard](https://automation-dashboard.vercel.app/cycle/266131)
```
This PR adds a config setting of `TestAutomationDashboardURL`. On deployment, it should have a value of …

E2E: Add link to test dashboard

---

server/fast_forward.go
server/fast_forward_test.go

Copied over ticket, It seems like there is a weird behavior that causes taking backup if there is no need to. Our decision-making algorithm works like this:
- Get the most recent backup branch
- Check if the  head commit is older than 5 days, If so take a backup
- Delete the cloud branch
- Create the backup
- Create a new cloud branch
In this case, if you run a `/cloud-ff` command, in the first run everything looks fine. But in the second run, it should be idempotent. But if the `master` branch has last commit more than 5 days ago, it's thinking that we haven't backed up that branch yet. Hence, creating new backups. We should look at the branch names here.
https://mattermost.atlassian.net/browse/MM-48376

cloud fast forward: check branch names instead of commit dates

---

config/config-mattermod.default.json
server/cherry_pick.go
server/config.go

Example of issue thrown: https://github.com/mattermost/mattermost-server/pull/22568#issuecomment-1488555380
We are configuring mattermod, to dynamically raise the limit `merge.renamelimit`. 
**merge.renamelimit**
_The number of files to consider in the exhaustive portion of rename detection during a merge. If not specified, defaults to the value of diff.renameLimit. If neither merge.renameLimit nor diff.renameLimit are specified, currently defaults to 7000. This setting has no effect if rename detection is turned off._
https://git-scm.com/docs/git-merge#Documentation/git-merge.txt-mergerenameLimit
Ticket: https://mattermost.atlassian.net/browse/CLD-5451

[CLD-5451] [feat] Ability to set git merge.renamelimit variable

---

.github/workflows/golangci-lint.yml
server/e2e_test_from_label.go
server/e2e_test_from_label_test.go
server/github.go

As per https://community.mattermost.com/core/pl/chexxbehjin5ffqo5kekeq9bqh, don't require a review to be able to run E2E tests. Running tests early should be encouraged help us catch issues early, reducing reviewer time.
None.

Require no reviews to e2e test

---

hack/cherry-pick.sh

This PR changes the cherry-picking script to push the automated cherry pick branches directly to the `upstream` repo, rather than its `origin` (which is assumed to be a fork; in fact this script originate from the [kubernetes community repo](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md), where contributions are obviously made from forks).
Example usage: [this PR](https://github.com/mattermost/test-private-project/pull/3) has been created by the following script.
```
export ORIGINAL_AUTHOR=mvitale1989
export GITHUB_USER=mvitale1989
export GITHUB_TOKEN=xxxxx
#export DRY_RUN=yes
git clone git@github.com:mattermost/test-private-project.git
cd test-private-project
git remote add upstream $(git remote get-url origin)
git fetch upstream
git …
```

CLD-6234 Cherrypick directly to upstream repo

---

server/cherry_pick.go

The previous PR worked, and mattermod is now able to create PRs directly against the repo (instead of its fork) for both public and private repos.
However,  some corollary operations (assigning reviewers, labeling the PR) do not work after merging the above change. Looking at the mattermod logs (which you can check out in [this comment](https://mattermost.atlassian.net/browse/CLD-6234?focusedCommentId=156788)) you can see that when mattermod tries to figure out the number of the PR it just created, it gets it wrong: e.g. it tries to send a POST request to `https://api.github.com/repos/mattermost/mattermost/issues/0/assign`.
The cause seems to be [this line](https://github.com/mattermost/mattermost-mattermod/blob/master/server/cherry_pick.go#L237): the regex …

CLD-6234 - Adapt PR regex to new cherrypick script

---

server/auto_merge.go

Various translations PRs are failing to merge automatically. In the logs, they seem to entirely disappear during the ticks, e.g.:
Add debug logging to the only exit point that currently fails to log in a bid to explain why this might be.
None.

Debug unsuccessful combined status state

---

Dockerfile

The following PR removed the user creation from mattermod's Dockerfile, since the new base (Ubuntu Noble) comes with its own `ubuntu` user out of the box: https://github.com/mattermost/mattermost-mattermod/pull/353/files
However, the mattermod helm chart assumes that the user with uid 1000 has its homedir in `/app`, and mounts some user-level configurations (e.g. `.gitconfig`) at that path.
So after the above change, mattermod is unable to do some operations, e.g. cherry-picking (because its looks for the ssh key it uses to pull from Github in `/home/ubuntu/.ssh/`, but the key is actually in `/app/.ssh/`): https://github.com/mattermost/mattermost/pull/25928#issuecomment-1964340153
Note that as an alternative, we could've instead changed the helm chart to mote the secrets to `/home/ubuntu` …

CLD-7237 Fix mattermod docker image
