mattermost/mattermost-mattermod

- server/spinmint.go
This is a proposal, and have some extra work in the spinmint configuration (another PR already done) and the jenkins configuration (Not done yet).
> Passing branch name to spinmint scripts

- config/config-mattermod.json
- server/config.go
- server/pull_request.go
- server/spinmint.go
Next stage is to refactor to use terraform. this is a quick and small win for now
> Add ability to deploy a test server and test the upgrade

- README.md
- server/pull_request.go
> https://github.com/mattermost/mattermost-server/issues/10339
PR Details:
- The issue comments created by Mattermod user are deleted when the label for the creation of the test server or the label for the upgrade of the test server is removed.
- The only issue comment remaining is the one specifying the termination of the test server.
- The issue comment about termination of a previous test server is deleted when a new label is applied. With the removal of old comments setup of test servers is successful. 
- Mattermod readme was updated to cover steps needed for local Mattermod testing.
> MM-14291 Improve mattermod test server setup

- Gopkg.lock
- Gopkg.toml
- config/config-mattermod.json
- mattermod.go
- server/config.go
- server/pull_request.go
- server/server.go
- server/spinmint.go
- vendor/gopkg.in/robfig/cron.v3/.gitignore
- vendor/gopkg.in/robfig/cron.v3/.travis.yml
- vendor/gopkg.in/robfig/cron.v3/LICENSE
- vendor/gopkg.in/robfig/cron.v3/README.md
- vendor/gopkg.in/robfig/cron.v3/constantdelay.go
- vendor/gopkg.in/robfig/cron.v3/cron.go
- vendor/gopkg.in/robfig/cron.v3/doc.go
- vendor/gopkg.in/robfig/cron.v3/go.mod
- vendor/gopkg.in/robfig/cron.v3/option.go
- vendor/gopkg.in/robfig/cron.v3/parser.go
- vendor/gopkg.in/robfig/cron.v3/spec.go
Add the initial replacement for the stale bot and other small changes
tested in my local instance and worked fine over the weekend
note: we need some big refactor in the mattermod code, but for now this is not in the scope
> Stale and others

- server/cla.go
> Minor grammar fix (need -> needs)

- config/config-mattermod.json
- server/config.go
- server/pull_request.go
- server/spinwick.go
This allows for mattermod to request different installation sizes
from the provisioner.
> Add HA SpinWick label option

- server/spinwick.go
> Show SpinWick test user data in a table

- server/spinwick.go
- server/utils.go
This change enhances mattermod logging for SpinWicks to include the
installation ID.
> Log installation IDs where possible

- server/pull_request.go
- server/spinmint.go
- server/spinwick.go
- create a label check function similar of the spinwick
- rename the removeSpinmintInfo to removeTestServerFromDB to make more sense
> small changes

- mattermod.go
- server/spinmint.go
was missing the deletion when is a spinwick, so we have some test server flying around....
> fix deletion test server on expire

- cloud/models.go
- server/pull_request.go
- server/spinwick.go
when upgrading and the request was an HA server we were not setting the license causing the deletion of the license in the cluster
> fix upgrade installation when is in ha mode

- server/github_pr.go
- server/issue.go
- server/server.go
https://github.com/mattermost/mattermost-server/issues/11921
https://mattermost.atlassian.net/browse/MM-17925
> MM-17925: Implement github ping event

- server/cherry_pick.go
See https://community.mattermost.com/core/pl/z5e1ijts5inm78h3oinewzo38y
> Update labels for cherry picks

- server/cherry_pick.go
Instead of requesting a random review, we now request the review form the original submitter, if we is an org member. If not, stick with the random review.
I did not test this PR, because I didn't know how.
See https://community.mattermost.com/core/pl/ehsyq4b7mib4pgj6sr69iqyeze
> Request review from original contributor for cherry pick PR

- server/cherry_pick.go
> Add Changelog/Not Needed and Docs/Not Needed to cherry-pick PR

- server/cherry_pick.go
I haven't tested this. Please double check.
> Add milestone to cherry-pick PR

- server/spinwick.go
with that we can setup other Mattermost repos to use the spinwicks
we need to merge this: https://github.com/mattermost/mattermost-server/pull/12903 before
notes:
maybe a follow up is to add a slash command that the user can set a version, for example, if they want a release-5.17 branch
> add ability to set a spinwick for other repositories

- config/config-mattermod.json
- mattermod.go
- server/auto_merge.go
- server/config.go
This will be a task that will run every 30 minutes to the PRs.
if the PRs have the auto-merge label and all the conditions met it will try to merge it. if fails it will post a message.
the conditions are:
- no left reviewers
- no blockers
- all checks pass
- all approved
> [IS-239] add auto merge PR feature

- server/auto_merge.go
- server/pull_request.go
See https://community.mattermost.com/core/pl/kt4oeko6s7ftpno8krwz6yk6yc
> Send comment when automerge labels is added

- server/cherry_pick.go
- server/cherry_pick_test.go
Fixing the trimming issue for mattermod cherry picking. Trimmed too much of the release string. Covered it also with tests.
> Fix cherry picking issue.

- config/config-mattermod.json
- config/config-mattermod.test-circleci.json
- config/config-mattermost.default.json
- server/build_mobile_apps.go
- server/cherry_pick.go
- server/circleci.go
- server/community.go
- server/config.go
- server/github.go
- server/update_branch.go
Add a separate org config setting, so `"mattermost"` is accessible as `s.Config.Org`
> IS-234: Add separate org config setting.

- server/build_mobile_apps.go
- server/circleci.go
Use a ticker for interval requesting the build link and artifact links resources from the circleci.
> IS-234: Adding ticker. Improve message.

- config/config-mattermod.json
- config/config-mattermod.test-circleci.json
- config/config-mattermost.default.json
- server/build_mobile_apps.go
- server/circleci.go
- server/config.go
Wait for the expected number of artifacts, before posting back the artifact links to pr.
> IS-234: Add expected amount of artifacts and logic to wait for it

- config/config-mattermod.json
- config/config-mattermod.test-circleci.json
- config/config-mattermost.default.json
- server/build_mobile_apps.go
- server/build_mobile_apps_test.go
- server/circleci.go
- server/circleci_test.go
- server/config.go
1. Check first for running builds
1. No running builds found, check for finished builds
1. Finished builds should have the expected amount of jobs and expected job names
1. Finished artifacts for each expected job should have the expected amount of artifacts
> IS-234: Use a different approach for building mobile apps.

- server/server.go
Trying a new approach on how to list PRs.
> IS-347: Different approach of endpoint. 

- server/server.go
Fixes https://mattermost.atlassian.net/browse/IS-347
> IS-347: Remove different approach.

- server/server.go
https://mattermost.atlassian.net/browse/IS-347
> IS-347: scream test over

- server/update_branch.go
Head up that I didn't test this locally as I don't know how.
Fixes https://github.com/mattermost/mattermost-mattermod/issues/73
> Allow submitter of a PR to user /update-branch

- config/config-mattermod.json
- config/config-mattermod.test-circleci.json
- config/config-mattermost.default.json
- server/circleci.go
- server/config.go
- server/enterprise.go
- server/pull_request.go
> IS-255: Trigger ee tests via label

- server/pull_request.go
> Is 255 debug

- server/enterprise.go
- server/pull_request.go
> IS-255: Just label.

- server/circleci.go
- server/enterprise.go
> IS-255: Fix auth

- server/enterprise.go
- server/pull_request.go
> IS-255: Remove preemptively removing the trigger success.

- server/circleci.go
- server/enterprise.go
> IS-255: Fix parameter mixup.

- server/enterprise.go
- server/pull_request.go
> IS-255: Fix label

- server/cherry_pick.go
- server/enterprise.go
- server/github.go
- server/pull_request.go
Mimicks the previous behavior of Jenkins for organization members to trigger the enterprise steps.
> IS-255: Auto trigger ee tests for org members.

- server/cherry_pick.go
With the migration to circleci, there seem to be some problems with the automatic cherrypicking. Disable it for now and inform the user.
> Disable cherry picking for now.

- server/github.go
https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref
Since we changed the review process to be pending, this check needs to be adapted.
> Fix mobile build review process.

- server/cherry_pick.go
Only the trigger related repositories are impacted. Reenable cherrypicking for the repositories which are not impacted.
> Enable cherrypicking for not impacted repositories.

- server/circleci.go
Remove feedback on every push.
> Run enterprise tests silently.

- config/config-mattermod.json
- config/config-mattermod.test-circleci.json
- config/config-mattermost.default.json
- server/circleci.go
- server/config.go
- server/enterprise.go
- server/github.go
Add logic to poll the build link for the triggered enterprise tests.
> IS-255: Poll build link

- server/circleci.go
- server/enterprise.go
- server/github.go
- server/pull_request.go
> Overall code improvements. 

- Makefile
- server/auto_merge.go
- server/autoassign.go
- server/block_pr_merge.go
- server/build_mobile_apps.go
- server/build_mobile_apps_test.go
- server/builds.go
- server/cherry_pick.go
- server/cherry_pick_test.go
- server/circleci.go
- server/circleci_test.go
- server/cla.go
- server/community.go
- server/enterprise.go
- server/github.go
- server/issue.go
- server/limit_rate_gh.go
- server/mocks/checks.go
- server/mocks/git.go
- server/mocks/issues.go
- server/mocks/organizations.go
- server/mocks/pull_requests.go
- server/mocks/repositories.go
- server/pull_request.go
- server/pull_request_test.go
- server/server.go
- server/update_branch.go
Fix so that not a new github client is created before every github request.
> Move gh client to server struct.

- Makefile
- mattermod.go
- server/cherry_pick.go
- server/community.go
- server/enterprise.go
- server/github.go
- server/github_client.go
- server/github_test.go
- server/mocks/checks.go
- server/mocks/organizations.go
- server/mocks/repositories.go
- server/pull_request.go
- server/server.go
- server/server_test.go
- server/update_branch.go
Implements the suggestion of @hanzei to save the org members and only refresh them on a daily basis. 
https://mattermost.atlassian.net/browse/IS-407
> Fix rate limit part 1

- server/server.go
Don't log org members daily
https://community.mattermost.com/private-core/pl/iomdeajhq3fopxuoez94o68gea
> Don't log org members

- server/cla.go
CLA github status will still be on pending even when excluded bot user. Succeeding the CLA github status is necessary for an excluded user.
> Succeed CLA status for excluded user.

- server/server.go
- server/spinmint.go
This PR changes how the AWS session is created. Now is created with the server instance and is located in the Server struct to avoid creating a new session every time
https://mattermost.atlassian.net/browse/MM-26418
> [MM-26418] Extract AWS Session creation

- config/config-mattermod.default.json
- go.mod
- go.sum
- server/auto_merge.go
- server/autoassign.go
- server/block_pr_merge.go
- server/build_mobile_apps.go
- server/builds.go
- server/cherry_pick.go
- server/circleci.go
- server/cla.go
- server/community.go
- server/config.go
- server/enterprise.go
- server/github.go
- server/issue.go
- server/limit_rate_gh.go
- server/pull_request.go
- server/pull_request_test.go
- server/server.go
- server/spinmint.go
- server/update_branch.go
- Refactor the use of context
- Create a consistent timeout
- AWS calls uses the `*WithContext` call
- ~Timeouts are configurable~
https://mattermost.atlassian.net/browse/MM-26417
> [MM-26417] Refactor use of context and add timeouts

- go.mod
- go.sum
- server/build_mobile_apps.go
- server/circleci.go
- server/circleci_test.go
- server/server.go
This PR includes the usage of the new *WithContext methods that have been introduced in the [last version](https://github.com/mattermost/go-circleci/pull/3) of go-circleci.
Also, the CircleCi client has been moved to the server struct and instantiate on server start to avoid creating a new client with every call to the CircleCi methods.
Finally, we've cleaned and updated the go.mod/sum 
https://mattermost.atlassian.net/browse/MM-26589
> [MM-26589] Use WithContext functions for CircleCi

- store/sql_pull_request_store.go
This PR adds a missing colmap not included in #154
> Add missing colmap

- server/block_pr_merge.go
- server/block_pr_merge_test.go
- server/pull_request.go
This PR includes:
- Tests for the `block_pr_merge` code
- Performs a little refactor to make easier to test some cases
https://mattermost.atlassian.net/browse/MM-26454
> [MM-26454] Add tests for block_pr_merge

- store/sql_issue_store_test.go
- store/sql_store_test.go
This PR adds tests for the Issue store
https://mattermost.atlassian.net/browse/MM-26577
> [MM-26577] Tests for Issue store

- server/github_pr.go
- server/pull_request.go
- server/server.go
This PR hpefully fixes the magical activity in the `handleAutoAssign` method. Tried to refactor the GitHub event handler function to be more readable and more reliable.
PS: We always need a PR issue number to be successful in `handleAutoAssign` see the old code [here](https://github.com/mattermost/mattermost-mattermod/blob/8d1283949607f2ed7abe2f5a09c833d389a2f57b/server/autoassign.go#L34).
https://mattermost.atlassian.net/browse/MM-26841
> [MM-26841] server: gently refactor github handler v1

- server/server.go
- server/server_test.go
https://mattermost.atlassian.net/browse/MM-26927
> MM-26927: Use a recovery middleware

- .gitlab-ci.yml
Add `.gitlb-ci.yaml` for deployment CI.
> Add .gitlab-ci configuration for deployment

- Makefile
- hack/release.sh
Add release helper Makefile targets and scripts.
- `release`: release specific version
- `patch`: release semver patch
- `minor`: release semver minor
- `major`: release semver major
> Add release targets and script

- .gitignore
- Makefile
- README.md
- Tiltfile
- deploy/base/app/deployment.yaml
- deploy/base/app/kustomization.yaml
- deploy/base/app/rbac.yaml
- deploy/base/app/service.yaml
- deploy/base/config/kustomization.yaml
- deploy/base/db/deployment.yaml
- deploy/base/db/kustomization.yaml
- deploy/base/db/pvc.yaml
- deploy/base/db/secrets.yaml
- deploy/base/db/service.yaml
- deploy/base/db/serviceaccount.yaml
- deploy/overlays/dev/kustomization.yaml
- deploy/overlays/dev/patches/service-nodeport.yaml
- deploy/overlays/prod/ingress.yaml
- deploy/overlays/prod/kustomization.yaml
- deploy/overlays/prod/patches/database-pvc.yaml
- deploy/overlays/prod/patches/deployment-replicas.yaml
- server/server.go
Add deployment manifests, developer local toolings guide.
> Add k8s manifests and dev tooling

- deploy/overlays/prod/kustomization.yaml
Fix typo of gitignored environment variables file.
> Fix typo in secretGenerator

- .gitignore
- deploy/overlays/prod/kustomization.yaml
Add missing required configuration files for production deployment.
> Add missing config files for prod deployment

- deploy/overlays/prod/kustomization.yaml
- deploy/overlays/prod/patches/database-pvc.yaml
Use RDS when deploying to production.
> Use RDS for prod deployment

- deploy/overlays/prod/kustomization.yaml
- deploy/overlays/prod/patches/deployment-config.yaml
Mount config files into deployment for production.
> Add required configuration to prod deployment

- server/validate_signature.go
https://mattermost.atlassian.net/browse/MM-27252
> MM-25272: Fix superfluous write header

- Dockerfile
- server/cherry_pick.go
Add missing `cherry_pick.sh` to the image at `/app/scripts/cherry_pick.sh`
> Add cherry_pick.sh, git and hub to the image

- Dockerfile
- deploy/overlays/prod/kustomization.yaml
- deploy/overlays/prod/patches/deployment-data-pvc.yaml
- deploy/overlays/prod/pvc.yaml
- server/cherry_pick.go
Add a persistent volume to deployment for local clones of repositories on disk.
> Mount /app/repos persistent volume into container

- server/server.go
https://mattermost.atlassian.net/browse/MM-27329
> MM-27329: Fix incorrect error check

- config/config-mattermod.default.json
This was another field which got missed out
> Adding AutoPRMergeLabel to default config

- server/pull_request.go
Added error to the log so we can know the real reason of the failing
https://mattermost.atlassian.net/browse/MM-27399
> Include error object in the error log for checkpractivity

- server/cherry_pick.go
- Log repo information when cherry pick fails. Makes it much easier to track down which PR's cherry-pick failed.
- N/A
> Log repo information when cherry pick fails

- deploy/overlays/prod/kustomization.yaml
- deploy/overlays/prod/patches/deployment-replicas.yaml
Because of how the rate limit handling is done right now, we need to work with 1 replica.
> Reduce replicas to 1.

- server/pull_request.go
- server/pull_request_test.go
Don't stop checking PR activity if one PR fails
https://mattermost.atlassian.net/browse/MM-27399
> [MM-27399] Don't break for iteration if one PR fails

- server/cherry_pick.go
- server/update_branch.go
- server/update_branch_test.go
I ended up with a slightly different approach I guess :) But we won't lose the actual error messages while passing errors to upper level :p 
https://mattermost.atlassian.net/browse/MM-26783
> [MM-26783] server/update_branch: tweak errors and messages

- server/github_test.go
- server/metrics.go
This PR fixes 2 issues.
1. We were always trying to read the response body irrespective of the status code.
This was unnecessary because a 200 response will not contain the response that we were expecting.
This would cause errors like "json: cannot unmarshal array into Go value of type struct"
2. In case of a failure, we were not resetting the body to be read further downstream which would
lead to errors like "http: read on closed response body"
> MM-27986: Fix error in reading non-403 responses

- server/auto_merge.go
- server/autoassign.go
- server/build_mobile_apps.go
- server/builds.go
- server/cherry_pick.go
- server/circleci.go
- server/cla.go
- server/enterprise.go
- server/github.go
- server/github_test.go
- server/issue_handler.go
- server/pull_request_handler.go
- server/spinmint.go
- server/update_branch.go
This was hanging for a while, let's get this out of the way.
https://mattermost.atlassian.net/browse/MM-26708
> [MM-26708] propogate errors upwards

- Makefile
- hack/release.sh
- server/server.go
- version/version.go
Add version information including actual version, commit hash, and build date to the built binary through ldfalgs on build time.
> Add version info, commit hash and build date to binary

- go.mod
- go.sum
- model/spinmint.go
- store/sql_spinmint_store.go
- store/sql_spinmint_store_test.go
- store/sql_store.go
- store/sql_store_test.go
mattermod: move away from gorp to sqlx in spinmint_store.go
Fixes [15566](https://github.com/mattermost/mattermost-server/issues/15566)
https://mattermost.atlassian.net/browse/MM-28977
> MM-28979 mattermod: move away from gorp to sqlx in spinmint_store.go

- config/config-mattermod.default.json
- server/cla.go
- server/cla_test.go
- server/community.go
- server/community_test.go
- server/config.go
- server/issue_comment_handler.go
- server/pull_request_handler.go
For all community PRs we want to send a welcome message to educate them about the review process.
The actual message send to the user can be found at https://github.com/mattermost/platform-private/pull/284.
Are there repository we want to don't post such message for? e.g. https://github.com/mattermost/docs
https://mattermost.atlassian.net/browse/MM-29076
> [MM-29076] Send welcome message for community PRs

- go.mod
- model/pull_request.go
- store/sql_issue_store_test.go
- store/sql_pull_request_store.go
- store/sql_pull_request_store_test.go
- store/sql_store.go
mattermod: move away from gorp to sqlx in pull_request_store.go
Fixes https://github.com/mattermost/mattermost-server/issues/15568
https://mattermost.atlassian.net/browse/MM-28977
I think there should be a separte issue to remove gorp from project, please let me know if you want to do it as pat of this PR.
> 15568 move-away-from-gorp-to-sqlx-in-pull_request_store

- go.tools.mod
- go.tools.sum
- server/enterprise.go
- store/migrations/bindata.go
> Add cloud-ga branch to need ee trigger.

- server/cherry_pick.go
- server/cherry_pick_test.go
Apply regex to find a specific command.
Fixes https://github.com/mattermost/mattermost-server/issues/16971
https://mattermost.atlassian.net/browse/MM-33008
> [MM-33008] apply strings to find command /cherry-pick

- .gitignore
- model/pull_request.go
- server/github.go
- server/pr_from_issue_handler_test.go
- server/pull_request_handler.go
- server/pull_request_handler_test.go
- server/update_branch.go
- server/update_branch_test.go
Reverts mattermost/mattermost-mattermod#257
Until https://github.com/mattermost/mattermost-mattermod/pull/260 is fixed.
> Revert "Use *bool for MaintainerCanModify "

- server/build_mobile_apps.go
making the branch unique when creating the mobile test app
JIRA: https://mattermost.atlassian.net/browse/DOPS-186
> making the branch unique when creating the mobile test app

- server/community.go
- server/community_test.go
This PR modifies the bot to add the contributor label _Contributor_ to all PRs and
issues filed by authors who are not in the org.
**Please note that this should not be merged until the label exists in all repos.**
Signed-off-by: Adolfo García Veytia (Puerco) <adolfo.garcia@mattermost.com>
https://mattermost.atlassian.net/browse/DOPS-262
> Add contributor label to all PRs

- .circleci/config.yml
- .golangci.yml
- Dockerfile
- Dockerfile.jobserver
- update go and golangci-lint
n/a
> update go and golangci-lint

- server/config.go
- server/e2e_test_command.go
There seem to have been some problems with the revert last time. This should fix it :crossed_fingers:
> E2E: Fix wait for loop by removing it, because we use combined status check.

- cmd/jobserver/main.go
- cmd/mattermost-mattermod/main.go
- config/config-mattermod.default.json
- server/auto_merge.go
- server/config.go
- server/translations.go
PR contains changes to automate weblate merge and cherry pick operations. 
1. If PR is created by weblate user, it adds do not merge label configured at configuration file.
2. Blocks merge operation by users.
3. Whenever PR is approved it will automerge with `merge` strategy. And removes label not to re-process PR.
4. Add `/cherry-pick cloud` comment to PR , so it will be picked into cloud branch.
5. With failure or success it will send a message to mattermost to notify translators.
JIRA: https://mattermost.atlassian.net/browse/DOPS-878
> Enhance mattermod for weblate pull requests management

- server/e2e_test_from_label.go
- server/e2e_test_from_label_test.go
- server/github.go
Added additional debug line, in case the upper case does not fix. Related docs:
https://docs.github.com/en/rest/pulls/reviews#list-reviews-for-a-pull-request
The inconsistency in upper case / lower case is weird on different api calls.
> Fix E2E test from label not finding approval :fingers-crossed:

- config/config-mattermod.default.json
- server/auto_merge.go
- server/config.go
We need to test weblate with different merge policies. For that make merge policy configurable.
> Make translation pr merge policy configurable

- server/config.go
- server/fast_forward.go
- server/fast_forward_test.go
We also need to update mattermod config:
```diff
diff --git a/config/config-mattermod.default.json b/config/config-mattermod.default.json
index 0e5cf4f..b5e8cc6 100644
--- a/config/config-mattermod.json
+++ b/config/config-mattermod.json
@@ -30,7 +30,22 @@
"GreetingLabels": []
}
],
-    "CloudRepositories": [],
+    "CloudRepositories": [{
+        "Name": "mattermost-server",
+        "MainBranch": "heads/master"
+    },{
+        "Name": "enterprise",
+        "MainBranch": "heads/master"
+    },{
+        "Name": "mattermost-webapp",
+        "MainBranch": "heads/master"
+    },{
+        "Name": "mattermost-api-reference",
+        "MainBranch": "heads/master"
+    },{
+        "Name": "focalboard",
+        "MainBranch": "heads/main"
+    }],
"BlockPRMergeLabels": [], …
```
> fix focalboard issue for main branch

- server/server.go
`server.go` is segfaulting due to evaluating nul pointers, while checking the value of `resp.NextPage`, in error state. 
```
mattermod-jobserver panic: runtime error: invalid memory address or nil pointer dereference
mattermod-jobserver [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xca419f]
mattermod-jobserver
mattermod-jobserver goroutine 201531 [running]:
mattermod-jobserver github.com/mattermost/mattermost-mattermod/server.(*Server).Tick(0xc0002362c0)
mattermod-jobserver 	/go/src/mattermod/server/server.go:262 +0x113f
mattermod-jobserver github.com/robfig/cron/v3.FuncJob.Run(0xc00007ccd0)
mattermod-jobserver 	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
mattermod-jobserver github.com/robfig/cron/v3.(*Cron).startJob.func1()
mattermod-jobserver …
```
> [fix] SEGFaulting when evaluating nul pointer

- server/circleci.go
Pass base branch (a.k.a. target branch) to the tbs (triggered by server) parameters.
> server/circleci: add base branch name into tbs parameters

- .github/workflows/golangci-lint.yml
- config/config-mattermod.default.json
- server/cherry_pick.go
- server/config.go
- server/e2e_cancel.go
- server/e2e_test_command.go
- server/e2e_test_desktop_command.go
- server/e2e_test_mobile_command.go
- server/fast_forward.go
- server/github.go
- server/github_test.go
- server/update_branch.go
https://mattermost.atlassian.net/browse/MM-50214
> MM-50214: Restrict slash command interpretation

- server/fast_forward.go
- server/fast_forward_test.go
https://mattermost.atlassian.net/browse/MM-52990
> [MM-52990] server/fast_forward: reflect new naming scheme changes on mattermost

- server/cherry_pick.go
And also bump the timeout now that
the main repo has increased in size.
> Fix inverted upstream and origin remotes

- Dockerfile
- Dockerfile.jobserver
Bump OS to address some vulnerabilities
https://mattermost.atlassian.net/browse/CLD-6283
> feat: Bump OS to bullseye

- Dockerfile
- Dockerfile.jobserver
Switching to ubuntu docker image to mitigate vulnerabilities
> fix: Switch docker image to ubuntu to mitigate vulnerabilities

- Dockerfile
Updated docker OS and Dockerfile to fix vulnerabilities
Ticket: https://mattermost.atlassian.net/browse/CLD-7569
> [chore] Updating base image
